

volumes:
  mc-server:

services:
  befoscraft:
    build: .
    container_name: befoscraft
    restart: unless-stopped
    networks:
      - minecraft-net
    tty: true
    stdin_open: true
    volumes:
      - ./mc-server:/server
    environment:
      EULA: "true"
      JVM_OPTS: "-Xmx3G -Xms1G"
    expose:
      - "25565"

networks:
  minecraft-net:
    external: true