

volumes:
  mc-server:

services:
  befoscraft:
    build: .
    container_name: befoscraft
    restart: unless-stopped
    networks:
      - minecraft-net
    tty: true
    stdin_open: true
    volumes:
      - ./mc-server:/server
    environment:
      EULA: "true"
      JVM_OPTS: "-Xmx3G -Xms1G"
    labels:
      infrarust.enable: "true"
      infrarust.domains: "befoscraft.juso-software.com"

networks:
  minecraft-net:
    external: true